// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import "crypto/x509"

type ClientIdentity struct {
	ID    string
	MspID string
}

func (fake *ClientIdentity) GetID() (string, error) {
	return fake.ID, nil
}

func (fake *ClientIdentity) GetMSPID() (string, error) {
	return fake.MspID, nil
}

func (fake *ClientIdentity) GetAttributeValue(attrName string) (value string, found bool, err error) {
	return "", false, nil
}

func (fake *ClientIdentity) AssertAttributeValue(attrName, attrValue string) error {
	return nil
}

func (fake *ClientIdentity) GetX509Certificate() (*x509.Certificate, error) {
	return nil, nil
}
